version: '3'
services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: root
      POSTGRES_DB: db
    container_name: db
    networks: 
      - production
    ports: 
      - "5432:5432"
  admin_production:
    image: adminer
    container_name: admin-production
    networks: 
      - production
    restart: always
    ports: 
      - "8080:8080"


networks: 
  production:


