version: '3.1'
services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: root
      POSTGRES_DB: db
    container_name: db
    ports:
      - "5432:5432"
  production:
    build: ../../app/api-node
    working_dir: /app
    environment: 
      NODE_ENV: production
    ports: 
      - "8080:8080"
    container_name: battlebots-node
    restart: always
#    command: wait-for-it/wait-for-it.sh db:5432 -- npm run start:docker
