version: '3'
services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_USER: root
      POSTGRES_DB: db
    container_name: db
    networks: 
      - gpe
    ports:
      - "5432:5432"
  production:
    build: ../../app/api-node
    working_dir: /app
    environment: 
      NODE_ENV: production
      ENV: prod
    ports: 
      - "8080:8080"
    container_name: battlebots-node
    networks: 
      - gpe
    restart: always
    command: wait-for-it/wait-for-it.sh db:5432 -- npm run start:docker

networks: 
  gpe:
    ipam:
      driver: default
      config:
        - subnet: "172.16.28.0/24"
